export const routes = {
  homePage: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgotPassword",
  resetPassword: "/resetPassword",
  products: "/products",
  brands: "/brands",
  articles: "/articles",
  customer: "/customer",
  manageProduct: "/manageProduct",
  manageOrder: "/manageOrder",
  manageArticle: "/manageArticle",
  manageVoucher: "/manageVoucher",
  manageAccount: "/manageAccount",
  cart: "/cart",
  staffHomePage: "/staff",
  staffChat: "/chatWithCustomer",
  manageGift: "/manageGift",
  staffBrandList: "/brand-list",
  updateProduct: "/updateProduct",
  addProduct: "/addProduct",
  checkout: "/checkout",
  statistics: "/statistics",
  manageMember: "/manageMember",
  manageStaff: "/manageStaff",
  searchProduct: "/search",
};
